# RH56H1 设备协议配置（与 RH56F1 寄存器一致）
protocol:
  type: RH56H1_485

devices:
  - name: hand_left
    port: /dev/ttyUSB0
    baudrate: 115200
    Hand_ID: 1

logging:
  level: ERROR
  file: logs/hand_control.log
  console: true
  file_enable: true
  max_file_size_mb: 10
  max_files: 5
